media: assets
content:
  - name: posts
    label: Posts
    type: collection
    path: _posts
    view:
      fields: [cover, title]
    fields:
      - name: layout
        type: string
        hidden: true
        default: post
      - name: cover
        label: Cover image
        type: image
      - name: title
        label: Title
        type: string
        required: true
      - name: categories
        label: Categories
        type: select
        options:
          values:
            - event
            - info
      - name: author
        label: Authors
        type: string
        list: true
      - name: meta
        label: Meta
        type: string
      - name: body
        label: Body
        type: rich-text
  - name: config
    label: Jekyll Configuration
    type: file
    path: _config.yml
    fields:
      - name: title
        label: Title
        type: string
        required: true
      - name: description
        label: Description
        type: string
      - name: url
        label: URL
        type: string
      - name: permalink
        label: Permalink Pattern
        type: string
        readonly: true
      - name: plugins
        label: Plugins
        type: string
        list: true
        readonly: true
      - name: header_pages
        label: Header Pages
        type: string
        list: true
