title: Das Stoffelhäusl
baseurl: ""
url: "http://stoffelhaeusl.info"
permalink: /neuigkeiten/:year/:month/:title

header_pages:
  - index.md
  - uebers-haus.md
  - neuigkeiten.md
  - galerie.md
  - kontakt.md
  - standort.md

# Build settings
markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-feed
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
