title: Das Stoffelhäusl
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /neuigkeiten/:year/:month/:title

header_pages:
  - index.md
  - uebers-haus.md
  - neuigkeiten.md
  - galerie.md
  - kontakt.md
  - standort.md

# Build settings
markdown: kramdown
sass:
  style: :compressed
gems:
  - jekyll-feed
exclude:
  - .gitignore
  - CNAME
  - Gemfile
  - Gemfile.lock
